package com.x1.frans.exception.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@AllArgsConstructor
@Getter
public enum ErrorCode {
    DUPLICATE_RESOURCE("DUPLICATE_RESOURCE", HttpStatus.CONFLICT),
    EMAIL_SEND_FAILED("EMAIL_SEND_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_USER_TYPE("INVALID_USER_TYPE", HttpStatus.BAD_REQUEST),
    INVALID_ADDRESS("INVALID_ADDRESS", HttpStatus.BAD_REQUEST),

    // 인증, 인가 관련 에러
    TOKEN_EXPIRED("TOKEN_EXPIRED", HttpStatus.UNAUTHORIZED),
    INVALID_TOKEN("INVALID_TOKEN", HttpStatus.UNAUTHORIZED),
    AUTH_FAILED("AUTH_FAILED", HttpStatus.UNAUTHORIZED),
    FORBIDDEN("FORBIDDEN", HttpStatus.FORBIDDEN),
    EXPIRED_REFRESH_TOKEN("EXPIRED_REFRESH_TOKEN", HttpStatus.UNAUTHORIZED),


    INVALID_TIME_FORMAT("INVALID_TIME_FORMAT", HttpStatus.BAD_REQUEST),
    DUPLICATE_DEADLINE_TIME("DUPLICATE_DEADLINE_TIME", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD("INVALID_PASSWORD", HttpStatus.UNAUTHORIZED),
    USER_NOT_FOUND("USER_NOT_FOUND", HttpStatus.NOT_FOUND),

    // 가맹점 관련 에러
    ENTITY_NOT_FOUND("ENTITY_NOT_FOUND", HttpStatus.NOT_FOUND),
    INVALID_FRANCHISE_ARGUMENT("INVALID_FRANCHISE_ARGUMENT", HttpStatus.BAD_REQUEST),

    // 공급처 관련 에러
    SUPPLIER_NOT_FOUND("SUPPLIER_NOT_FOUND", HttpStatus.NOT_FOUND),
    UNAUTHORIZED_ACCESS("UNAUTHORIZED_ACCESS", HttpStatus.NOT_FOUND),
    INVALID_SUPPLIER_ARGUMENT("INVALID_SUPPLIER_ARGUMENT", HttpStatus.BAD_REQUEST);

    private final String code;
    private final HttpStatus httpStatus;

}
