package com.x1.frans.exception.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@AllArgsConstructor
@Getter
public enum ErrorCode {
    DUPLICATE_RESOURCE("DUPLICATE_RESOURCE", HttpStatus.CONFLICT),
    EMAIL_SEND_FAILED("EMAIL_SEND_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_USER_TYPE("INVALID_USER_TYPE", HttpStatus.BAD_REQUEST),
    INVALID_ADDRESS("INVALID_ADDRESS", HttpStatus.BAD_REQUEST),

    // 인증, 인가 관련 에러
    TOKEN_EXPIRED("TOKEN_EXPIRED", HttpStatus.UNAUTHORIZED),
    INVALID_TOKEN("INVALID_TOKEN", HttpStatus.UNAUTHORIZED),
    AUTH_FAILED("AUTH_FAILED", HttpStatus.UNAUTHORIZED),
    FORBIDDEN("FORBIDDEN", HttpStatus.FORBIDDEN),
    EXPIRED_REFRESH_TOKEN("EXPIRED_REFRESH_TOKEN", HttpStatus.UNAUTHORIZED),
    ACCOUNT_LOCKED("ACCOUNT_LOCKED", HttpStatus.UNAUTHORIZED),
    ACCOUNT_DELETED("ACCOUNT_DELETED", HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED("ACCESS_DENIED", HttpStatus.FORBIDDEN),

    INVALID_TIME_FORMAT("INVALID_TIME_FORMAT", HttpStatus.BAD_REQUEST),
    DUPLICATE_DEADLINE_TIME("DUPLICATE_DEADLINE_TIME", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD("INVALID_PASSWORD", HttpStatus.UNAUTHORIZED),
    USER_NOT_FOUND("USER_NOT_FOUND", HttpStatus.NOT_FOUND),

    // 가맹점 관련 에러
    ENTITY_NOT_FOUND("ENTITY_NOT_FOUND", HttpStatus.NOT_FOUND),
    INVALID_FRANCHISE_ARGUMENT("INVALID_FRANCHISE_ARGUMENT", HttpStatus.BAD_REQUEST),
    FRANCHISE_UNAUTHORIZED_ACCESS("UNAUTHORIZED_ACCESS", HttpStatus.UNAUTHORIZED),

    // 자재 관련 에러
    PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND", HttpStatus.NOT_FOUND),
    DUPLICATE_PRODUCT_CODE("DUPLICATE_PRODUCT_CODE", HttpStatus.CONFLICT),
    INVALID_PRODUCT_ARGUMENT("INVALID_PRODUCT_ARGUMENT", HttpStatus.BAD_REQUEST),
    INACTIVE_PRODUCT_ACCESS("INACTIVE_PRODUCT_ACCESS", HttpStatus.FORBIDDEN),

    // 공급처 관련 에러
    SUPPLIER_NOT_FOUND("SUPPLIER_NOT_FOUND", HttpStatus.NOT_FOUND),
    SUPPLIER_UNAUTHORIZED_ACCESS("UNAUTHORIZED_ACCESS", HttpStatus.NOT_FOUND),
    INVALID_SUPPLIER_ARGUMENT("INVALID_SUPPLIER_ARGUMENT", HttpStatus.BAD_REQUEST),

    // 주문 관련 에러
    INVALID_ORDER_REJECT_CONDITION("INVALID_ORDER_REJECT_CONDITION", HttpStatus.BAD_REQUEST),
    ORDER_REJECT_REASON_REQUIRED("ORDER_REJECT_REASON_REQUIRED", HttpStatus.BAD_REQUEST),
    ORDER_NOT_FOUND("ORDER_NOT_FOUND", HttpStatus.NOT_FOUND),
    ORDER_DEADLINE_TIME_NOT_FOUND("ORDER_DEADLINE_TIME_NOT_FOUND", HttpStatus.NOT_FOUND),
    INVALID_REQUEST("INVALID_REQUEST", HttpStatus.BAD_REQUEST),

    // 창고 관련 에러
    DEPARTMENT_NOT_FOUND("DEPARTMENT_NOT_FOUND", HttpStatus.BAD_REQUEST),
    INVALID_DEPARTMENT("INVALID_DEPARTMENT", HttpStatus.FORBIDDEN),
    WAREHOUSE_NOT_FOUND("WAREHOUSE_NOT_FOUND", HttpStatus.NOT_FOUND),

    // 발주 관련 에러
    PURCHASE_REQUEST_NOT_FOUND("PURCHASE_REQUEST_NOT_FOUND", HttpStatus.NOT_FOUND),
    CANNOT_CHANGE_TO_DRAFT("CANNOT_CHANGE_TO_DRAFT", HttpStatus.BAD_REQUEST),
    INVALID_PURCHASE_REQUEST_STATUS("INVALID_PURCHASE_REQUEST_STATUS", HttpStatus.BAD_REQUEST),
    PRODUCT_SUPPLIER_MISMATCH("PRODUCT_SUPPLIER_MISMATCH", HttpStatus.BAD_REQUEST),
    INVALID_PURCHASE_REQUEST_PRODUCT("INVALID_PURCHASE_REQUEST_PRODUCT", HttpStatus.BAD_REQUEST),
    PURCHASE_ORDER_NOT_FOUND("PURCHASE_ORDER_NOT_FOUND", HttpStatus.NOT_FOUND),
    CANNOT_DELETE_ORDER("CANNOT_DELETE_ORDER", HttpStatus.BAD_REQUEST),
    INVALID_ORDER_STATUS("INVALID_ORDER_STATUS", HttpStatus.BAD_REQUEST),
    CANNOT_CANCEL_PURCHASE_ORDER("CANNOT_CANCEL_PURCHASE_ORDER", HttpStatus.BAD_REQUEST),

    // 반품 관련 에러
    INVALID_RETURN_REJECT_CONDITION("INVALID_REJECT_CONDITION", HttpStatus.BAD_REQUEST),
    INVALID_RETURN_ARGUMENT("INVALID_RETURN_ARGUMENT", HttpStatus.BAD_REQUEST),

    // AWS 관련 에러
    FILE_UPLOAD_FAILED("FILE_UPLOAD_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_FILE_EXTENSION("INVALID_FILE_EXTENSTION", HttpStatus.BAD_REQUEST),
    INVALID_FILE_UPLOAD_TYPE("INVALID_FILE_UPLOAD_TYPE", HttpStatus.BAD_REQUEST),

    // 통계 관련 에러
    STATISTICS_UNAUTHORIZED_ACCESS("STATISTICS_UNAUTHORIZED_ACCESS", HttpStatus.FORBIDDEN),
    NOT_FOUND_STATISTICS("NOT_FOUND_STATISTICS", HttpStatus.NOT_FOUND),

    // 알림 관련 에러
    NO_DELETABLE_MESSAGES("NO_DELETABLE_MESSAGES", HttpStatus.BAD_REQUEST),
    NO_PERMISSION_OR_NONE_EXIST("NO_PERMISSION_OR_NONE_EXIST", HttpStatus.FORBIDDEN),
    UNREAD_MESSAGES_CANNOT_BE_DELETED("UNREAD_MESSAGES_CANNOT_BE_DELETED", HttpStatus.BAD_REQUEST),
    ALL_MESSAGES_ALREADY_READ("ALL_MESSAGES_ALREADY_READ", HttpStatus.BAD_REQUEST),

    // 결재 관련 에러
    APPROVAL_NOT_FOUND("APPROVAL_NOT_FOUND", HttpStatus.NOT_FOUND),
    APPROVAL_LINE_NOT_FOUND("APPROVAL_LINE_NOT_FOUND", HttpStatus.NOT_FOUND),
    APPROVAL_ACTION_FAILED("APPROVAL_ACTION_FAILED", HttpStatus.BAD_REQUEST),
    APPROVAL_LINE_TEMPLATE_ACTION_FAILED("APPROVAL_LINE_TEMPLATE_ACTION_FAILED", HttpStatus.BAD_REQUEST),
    APPROVAL_LINE_TEMPLATE_NOT_FOUND("APPROVAL_LINE_TEMPLATE_NOT_FOUND", HttpStatus.NOT_FOUND),
    UNAUTHORIZED_TEMPLATE_ACCESS("UNAUTHORIZED_TEMPLATE_ACCESS", HttpStatus.UNAUTHORIZED),

    // 출고 관련 에러
    OUTBOUND_NOT_FOUND("OUTBOUND_NOT_FOUND", HttpStatus.NOT_FOUND),

    // 납품 관련 에러
    EMPTY_DELIVERY_ITEM("EMPTY_DELIVERY_ITEM", HttpStatus.NOT_FOUND),
    NOT_FOUND_DELIVERY_INFO("NOT_FOUND_DELIVERY_INFO", HttpStatus.NOT_FOUND),
    CANNOT_MODIFY_DELIVERY_INFO("CANNOT_MODIFY_DELIVERY_INFO", HttpStatus.BAD_REQUEST),
    INVALID_SEARCH_PERIOD("INVALID_SEARCH_PERIOD", HttpStatus.BAD_REQUEST);

    private final String code;
    private final HttpStatus httpStatus;

}
